# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET http://localhost:8000/toys/
Accept: application/json

###

GET http://localhost:8000/toys/
Accept: text/html

###

OPTIONS http://localhost:8000/toys/1

###

GET http://localhost:8000/competitions/?pilot_name=Penelope+Pitstop&drone_name=WonderDrone
Accept: application/json

###

POST http://localhost:8000/drones/
Content-Type: application/json
Authorization: Basic djangosuper passwordforsuper

{
  "name": "Python Drone",
  "drone_category": "Quadcopter",
  "manufacturing_date": "2017-08-14T10:46:00.716312Z",
  "has_it_competed": "false"
}

###

PATCH http://localhost:8000/drones/2
Content-Type: application/json
Authorization: Basic djangosuper passwordforsuper

{
  "has_it_competed":"true"
}

###

GET http://localhost:8000/drones/2
Accept: application/json

###

GET http://localhost:8000/pilots/
Authorization: Token 27a0848a86b10d8da4b04d895c1428a872230599
Accept: application/json

###

GET http://localhost:8000/competitions/
Accept: application/json
Authorization: Basic djangosuper passwordforsuper

###

GET http://localhost:8000/competitions/
Accept: application/json

###